apiVersion: v1
kind: Service
metadata:
  name: golang-app
  labels:
    app: golang-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: golang-app
